language: groovy
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
before_install:
  chmod +x gradlew
env:
  global:
    - secure: "cBrXDV4ylU13IdF3yiVZvbVmkcXxnh7uEdC3PBELvORvxEh//1pG2sHntByIvbRQmP0Ea20eHyJA2bb1uWawsvBN3RjlpO9TfEknkY5YKgxkBZHrv7muSznU2L89nIqM1zt9li18RhaWJ/YYhArXyuvRW507o2FISaPGZLR0Kto="
    - secure: "TUFvtQqTxkkOLTxEXt6uNJLzBu+ERpM1pokSXKXlxrv0NCm+xLmMnP02ci1+wJT60Aes6dpog5Zsf1jA9zazkwh9eUA01wTL/KKnkc6zlI9P1eHwn8ReK1tBVs6Bg6kjcGZfovApjGo5mVvybEhMoccpH3fbQc9GH9aj3HjR5Uw="
  - JAVA_OPTS="-XX:PermSize=256M -XX:MaxPermSize=512M"

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew artifactoryPublish -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY}
  on:
    branch: master
    jdk: oraclejdk8
